import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const gillSans = localFont({
    src: [
        {
            path: './fonts/gill-sans.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/gill-sans-italic.otf',
            weight: '400',
            style: 'italic',
        },
        {
            path: './fonts/gill-sans-light.otf',
            weight: '300',
            style: 'normal',
        },
        {
            path: './fonts/gill-sans-bold.otf',
            weight: '700',
            style: 'normal',
        },
        {
            path: './fonts/gill-sans-bold-italic.otf',
            weight: '700',
            style: 'italic',
        },
    ],
    variable: '--font-gill-sans'
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${gillSans.variable} antialiased`}
        >
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}